import { DisasterIncident, SOSBeacon, Shelter, ReliefItem, EmergencyBroadcast } from '../types/disaster';

export const INITIAL_INCIDENTS: DisasterIncident[] = [
  {
    id: 'INC-2026-081',
    title: 'Silver Ridge Wildfire Complex',
    type: 'wildfire',
    severity: 'Catastrophic',
    status: 'active',
    region: 'North Sierra Corridor / Zone 4',
    coordinates: {
      lat: 38.8951,
      lng: -120.7324,
      x: 32,
      y: 28,
    },
    affectedPopulation: 42500,
    displacedPersons: 14200,
    casualties: {
      injured: 28,
      missing: 5,
      confirmedSafe: 14167,
    },
    evacuationStatus: 'Mandatory Evacuation',
    telemetry: {
      windSpeedKmH: 68,
      radiusKm: 24,
      tempC: 39,
      airQualityAqi: 342,
    },
    dispatchedUnits: {
      sarTeams: 14,
      fireEngines: 42,
      medicalUnits: 18,
      helicopters: 6,
      amphibiousVehicles: 0,
    },
    reportedAt: '2026-10-06 04:15 UTC',
    lastUpdate: '12 mins ago',
    description: 'Dry lightning ignited heavy timber fuel in steep canyon terrain. Strong downslope gusts are driving fire behavior southwest toward residential ridges.',
    incidentCommander: 'Chief Batt. Elena Vance (CAL-FIRE Taskforce 3)',
    actionLog: [
      { id: '1', time: '10 mins ago', message: 'Aerial water-dropping operations resumed as canyon smoke lifted slightly.', author: 'Air Ops Unit 4' },
      { id: '2', time: '34 mins ago', message: 'Zone 4-B shifted from voluntary to mandatory evacuation.', author: 'Commander Vance' },
      { id: '3', time: '2 hours ago', message: 'Sector containment perimeter reinforced with bulldozer firebreak.', author: 'Dozer Team 7' },
    ],
  },
  {
    id: 'INC-2026-082',
    title: 'Cascadia Basin Flash Flood',
    type: 'flood',
    severity: 'Severe',
    status: 'active',
    region: 'River Valley & Lower Plain / Zone 1',
    coordinates: {
      lat: 37.9821,
      lng: -121.2891,
      x: 64,
      y: 62,
    },
    affectedPopulation: 68000,
    displacedPersons: 9400,
    casualties: {
      injured: 14,
      missing: 3,
      confirmedSafe: 9383,
    },
    evacuationStatus: 'Mandatory Evacuation',
    telemetry: {
      waterLevelM: 4.8,
      radiusKm: 32,
      airQualityAqi: 48,
    },
    dispatchedUnits: {
      sarTeams: 22,
      fireEngines: 8,
      medicalUnits: 12,
      helicopters: 4,
      amphibiousVehicles: 15,
    },
    reportedAt: '2026-10-06 18:30 UTC',
    lastUpdate: '5 mins ago',
    description: 'Catastrophic atmospheric river rainfall dumped 180mm in 12 hours. The Miller Creek Levee has sustained micro-breaches inundating low-lying roadways.',
    incidentCommander: 'Director Marcus Thorne (State Emergency Operations)',
    actionLog: [
      { id: '1', time: '5 mins ago', message: 'High-water amphibious vehicles deployed to extract 18 stranded motorists at Highway 12 cut-off.', author: 'Water SAR Squad 3' },
      { id: '2', time: '45 mins ago', message: 'Army Corps of Engineers deploying emergency sandbag containment at levee mile marker 14.', author: 'Eng Corps Dispatch' },
      { id: '3', time: '3 hours ago', message: 'Flash flood sirens sounded across low-elevation residential zones.', author: 'EOC Comm' },
    ],
  },
  {
    id: 'INC-2026-083',
    title: 'San Gregorio Fault Seism (M6.4)',
    type: 'earthquake',
    severity: 'Severe',
    status: 'monitoring',
    region: 'Coastal Peninsula Sector / Zone 2',
    coordinates: {
      lat: 37.4529,
      lng: -122.3814,
      x: 18,
      y: 72,
    },
    affectedPopulation: 120000,
    displacedPersons: 3100,
    casualties: {
      injured: 46,
      missing: 1,
      confirmedSafe: 3053,
    },
    evacuationStatus: 'Shelter-in-Place',
    telemetry: {
      magnitudeRichter: 6.4,
      radiusKm: 45,
      airQualityAqi: 62,
    },
    dispatchedUnits: {
      sarTeams: 18,
      fireEngines: 15,
      medicalUnits: 25,
      helicopters: 3,
      amphibiousVehicles: 0,
    },
    reportedAt: '2026-10-07 01:10 UTC',
    lastUpdate: '28 mins ago',
    description: 'Strong seismic rupture at 9.2km focal depth. Multiple brick facades collapsed, localized gas main breaches isolated, structural assessments underway.',
    incidentCommander: 'Deputy Chief Sarah Lin (Urban Search & Rescue TF-1)',
    actionLog: [
      { id: '1', time: '28 mins ago', message: 'Overpass structural safety certified; secondary emergency route reopened.', author: 'DOT Inspection Unit' },
      { id: '2', time: '1 hour ago', message: 'Acoustic search dogs combed collapsed masonry at 4th & Mission.', author: 'K-9 Search Team' },
      { id: '3', time: '2 hours ago', message: 'Main gas line shutoff confirmed across grid sectors 2A and 2B.', author: 'Gas Utility Lead' },
    ],
  },
  {
    id: 'INC-2026-084',
    title: 'Industrial Rail Ammonia Hazmat Release',
    type: 'chemical_leak',
    severity: 'Moderate',
    status: 'contained',
    region: 'Harbor Freight Terminal / Zone 5',
    coordinates: {
      lat: 37.7915,
      lng: -122.2531,
      x: 78,
      y: 22,
    },
    affectedPopulation: 18500,
    displacedPersons: 1200,
    casualties: {
      injured: 8,
      missing: 0,
      confirmedSafe: 1192,
    },
    evacuationStatus: 'Shelter-in-Place',
    telemetry: {
      radiusKm: 6,
      windSpeedKmH: 14,
      airQualityAqi: 188,
    },
    dispatchedUnits: {
      sarTeams: 4,
      fireEngines: 12,
      medicalUnits: 8,
      helicopters: 1,
      amphibiousVehicles: 0,
    },
    reportedAt: '2026-10-06 21:00 UTC',
    lastUpdate: '40 mins ago',
    description: 'Pressurized anhydrous ammonia car valve leak during coupling operations. Hazmat foam barrier deployed; plume dispersion modeling shows containment inside industrial buffer.',
    incidentCommander: 'Hazmat Captain David Ross (Industrial Response Group)',
    actionLog: [
      { id: '1', time: '40 mins ago', message: 'Atmospheric sensors indicate vapor concentration dropped below IDLH threshold.', author: 'Hazmat Team 1' },
      { id: '2', time: '2 hours ago', message: 'Vapor suppression water fog curtains established around rail spur.', author: 'Engine 14' },
    ],
  },
];

export const INITIAL_BEACONS: SOSBeacon[] = [
  {
    id: 'SOS-901',
    citizenName: 'Eleanor Campbell',
    contact: '(555) 392-8819',
    locationText: '482 Pine Needle Rd, Apt 3B, Silver Ridge',
    x: 35,
    y: 31,
    priority: 'Critical',
    peopleCount: 3,
    hasMedicalNeed: true,
    isTrapped: true,
    notes: 'Elderly grandmother on oxygen concentrator with power outage. Fire front approaching within 800m. Road cut off by fallen pines.',
    timestamp: '8 mins ago',
    status: 'pending',
  },
  {
    id: 'SOS-902',
    citizenName: 'David & Sofia Mendez',
    contact: '(555) 714-2201',
    locationText: 'River Road Mile 11, near Old Mill Bridge',
    x: 66,
    y: 65,
    priority: 'Critical',
    peopleCount: 4,
    hasMedicalNeed: false,
    isTrapped: true,
    notes: 'Subaru SUV submerged to hood in rapid floodwater. 2 adults and 2 children on vehicle roof.',
    timestamp: '14 mins ago',
    status: 'responding',
    assignedSquad: 'Amphibious Unit 04',
  },
  {
    id: 'SOS-903',
    citizenName: 'Jordan Vance',
    contact: '(555) 902-4411',
    locationText: '882 Oak Avenue, Historic District',
    x: 21,
    y: 74,
    priority: 'Urgent',
    peopleCount: 2,
    hasMedicalNeed: true,
    isTrapped: false,
    notes: 'Chimney collapsed through living room ceiling during tremor. Minor lacerations treated with first aid kit, requiring transport assistance.',
    timestamp: '32 mins ago',
    status: 'pending',
  },
  {
    id: 'SOS-904',
    citizenName: 'Karen Lin',
    contact: '(555) 601-3320',
    locationText: 'Community Church Shelter Annex',
    x: 52,
    y: 42,
    priority: 'Standard',
    peopleCount: 6,
    hasMedicalNeed: false,
    isTrapped: false,
    notes: 'Family evacuated successfully, request confirmation of infant formula supplies at Westside Arena.',
    timestamp: '1 hour ago',
    status: 'rescued',
  },
];

export const INITIAL_SHELTERS: Shelter[] = [
  {
    id: 'SHL-01',
    name: 'Westside Civic Arena & Evacuation Hub',
    address: '1400 Exposition Blvd, Sector 3',
    x: 48,
    y: 44,
    capacity: 1200,
    currentOccupancy: 864,
    hasMedicalStaff: true,
    isPetFriendly: true,
    powerStatus: 'Grid Operational',
    suppliesDaysRemaining: 6,
    contactPhone: '(555) 490-1100',
    managerName: 'Rachel Adams',
  },
  {
    id: 'SHL-02',
    name: 'North Valley Regional High Gymnasium',
    address: '820 Mountain Vista Way, Sector 1',
    x: 26,
    y: 20,
    capacity: 650,
    currentOccupancy: 610,
    hasMedicalStaff: true,
    isPetFriendly: false,
    powerStatus: 'Generator Active',
    suppliesDaysRemaining: 3,
    contactPhone: '(555) 490-1102',
    managerName: 'Thomas Clark',
  },
  {
    id: 'SHL-03',
    name: 'St. Jude Community Center & Field Clinic',
    address: '304 Mission Square, Sector 2',
    x: 22,
    y: 68,
    capacity: 400,
    currentOccupancy: 215,
    hasMedicalStaff: true,
    isPetFriendly: true,
    powerStatus: 'Grid Operational',
    suppliesDaysRemaining: 7,
    contactPhone: '(555) 490-1105',
    managerName: 'Sister Maria Teresa',
  },
  {
    id: 'SHL-04',
    name: 'Fairgrounds Livestock & Companion Animal Shelter',
    address: '2200 Agricultural Way, Sector 4',
    x: 72,
    y: 50,
    capacity: 850,
    currentOccupancy: 390,
    hasMedicalStaff: false,
    isPetFriendly: true,
    powerStatus: 'Generator Active',
    suppliesDaysRemaining: 5,
    contactPhone: '(555) 490-1109',
    managerName: 'Dr. Kevin Sterling (DVM)',
  },
];

export const INITIAL_RELIEF_ITEMS: ReliefItem[] = [
  { id: 'REL-01', name: 'Potable Water Packs (10L Containers)', category: 'Water', inStock: 14200, unit: 'units', criticalThreshold: 4000, assignedSector: 'Sector 1 & 4' },
  { id: 'REL-02', name: 'Ready-to-Eat Emergency Meals (MREs)', category: 'Food Rations', inStock: 28500, unit: 'meals', criticalThreshold: 6000, assignedSector: 'All Hubs' },
  { id: 'REL-03', name: 'Tactical Trauma First Aid Kits', category: 'Medical', inStock: 1840, unit: 'kits', criticalThreshold: 500, assignedSector: 'Field Clinics' },
  { id: 'REL-04', name: 'Emergency Blankets & Cots', category: 'Shelter Kits', inStock: 3200, unit: 'sets', criticalThreshold: 800, assignedSector: 'Civic Arena' },
  { id: 'REL-05', name: 'Diesel Fuel for Backup Generators', category: 'Power/Fuel', inStock: 8600, unit: 'gallons', criticalThreshold: 2000, assignedSector: 'Hospitals & Shelters' },
  { id: 'REL-06', name: 'N95 Particulate Respirator Boxes', category: 'Medical', inStock: 12000, unit: 'boxes', criticalThreshold: 2500, assignedSector: 'Fire Perimeter' },
];

export const INITIAL_BROADCASTS: EmergencyBroadcast[] = [
  {
    id: 'EAS-2026-001',
    headline: 'MANDATORY EVACUATION: Silver Ridge Canyon & Pine Crest Ridge',
    severity: 'Catastrophic',
    disasterType: 'wildfire',
    issuedAt: '2026-10-07 04:30 PDT',
    expiresAt: '2026-10-07 20:00 PDT',
    targetCounties: ['Placer County', 'El Dorado Ridge', 'Zones 4A - 4D'],
    mandatoryInstructions: 'Leave immediately via Highway 50 Eastbound. Do not delay to gather personal items. If road blocked, report to North Valley High shelter.',
    activeChannels: ['Cell Broadcast', 'NOAA Radio', 'Sirens', 'Digital Signs'],
    acknowledgedCount: 84120,
  },
  {
    id: 'EAS-2026-002',
    headline: 'FLASH FLOOD EMERGENCY: Miller Creek & Cascadia River Basin',
    severity: 'Severe',
    disasterType: 'flood',
    issuedAt: '2026-10-07 02:15 PDT',
    expiresAt: '2026-10-07 14:00 PDT',
    targetCounties: ['Cascadia Delta', 'Highway 12 Corridor'],
    mandatoryInstructions: 'Move to higher ground immediately. Do not attempt to walk, swim, or drive through flooded waters. 15cm of moving water can knock down an adult.',
    activeChannels: ['Cell Broadcast', 'Sirens', 'Digital Signs'],
    acknowledgedCount: 61900,
  },
];
